### PR TITLE
docs(README): updating for testing, JS Idiomatic Style, and added som…

### PR DESCRIPTION
**Pull request by jkurz**
Updating the README with some things I found and some extra information on testing.

### CODE REVIEW

**Comment by jamsyoung** [comment]
I couple of comments.

In the 2nd note, make that clear that you are referring to browser side code.  There is no reason not to use the stable ES6 components that are part of io.js.

The Testing Facility should probably be split into two different sections.  One for server side node based projects, which will only use Mocha/Chai, and another for front end client (angular) projects, which will use Karma and Protractor.

Thanks for all the other updates!

**Comment by jamsyoung** [comment]
Also, the xkcd image is now rendering as a broken image with the URL pulled out to a reference.

**Comment by jkurz** [comment]
So we support io.js or running node with the --harmony flag turned on? It seems to me, even on the server this is an iffy subject.

**Comment by jamsyoung** [comment]
No, we only support what is standard in io.js, no --harmony flag (which they actually removed and replaced with --es_staging).

**Comment by jkurz** [comment]
This has been updated as requested.

**Pull request closed without merging**
